<?php
$z[0]=Array("field","奥运火炬伊斯坦布尔传递,萨厄尔",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","奥运火炬伊斯坦布尔传递 萨厄尔点燃圣火盆[暂无简介]",72,165);
$z[1][4]['name']="description";
$z[2]=Array("field","奥运火炬伊斯坦布尔传递 萨厄尔点燃圣火盆",167,244);
$z[2][4]['name']="title";
$z[3]=Array("field","",246,285);
$z[3][4]['name']="writer";
$z[4]=Array("field","",287,326);
$z[4][4]['name']="source";
$z[5]=Array("field","",328,368);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<P><img src=\"/uploads/allimg/c111027/1319645FL20-154J.jpg\" border=0><BR></P><P>　4月3日，在圣火传递终点――塔克希姆广场，最后一棒火炬手、土耳其著名举重运动员、雅典奥运会男子77公斤级金牌得主塔内尔·萨厄尔点燃圣火盆。当日，<A class=akey href=\"http://2008.sina.com.cn/\" target=_blank>北京奥运会</A>圣火境外传递第二站在土耳其伊斯坦布尔结束。 </P><P>　　新华社记者安治平摄</P><P>&lt;--正文内容结束--&gt;&lt;--关于内容的操作开始--&gt;&lt;--发表评论开始--&gt;</P>",370,863);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c111027/1319645FL20-154J_lit.jpg",865,952);
$z[7][4]['name']="litpic";

?>