{dede:field name='keywords'}奥运火炬伊斯坦布尔传递,萨厄尔{/dede:field}
{dede:field name='description'}奥运火炬伊斯坦布尔传递 萨厄尔点燃圣火盆[暂无简介]{/dede:field}
{dede:field name='title'}奥运火炬伊斯坦布尔传递 萨厄尔点燃圣火盆{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<P><img src="/uploads/allimg/c111027/1319645FL20-154J.jpg" border=0><BR></P><P>　4月3日，在圣火传递终点――塔克希姆广场，最后一棒火炬手、土耳其著名举重运动员、雅典奥运会男子77公斤级金牌得主塔内尔·萨厄尔点燃圣火盆。当日，<A class=akey href="http://2008.sina.com.cn/" target=_blank>北京奥运会</A>圣火境外传递第二站在土耳其伊斯坦布尔结束。 </P><P>　　新华社记者安治平摄</P><P>&lt;--正文内容结束--&gt;&lt;--关于内容的操作开始--&gt;&lt;--发表评论开始--&gt;</P>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c111027/1319645FL20-154J_lit.jpg{/dede:field}
