<?php
$z[0]=Array("field","心中有“家”甘奉献,真爱无私铸",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","心中有“家”甘奉献 真爱无私铸警魂[暂无简介]",72,159);
$z[1][4]['name']="description";
$z[2]=Array("field","心中有“家”甘奉献 真爱无私铸警魂",161,232);
$z[2][4]['name']="title";
$z[3]=Array("field","",234,273);
$z[3][4]['name']="writer";
$z[4]=Array("field","",275,314);
$z[4][4]['name']="source";
$z[5]=Array("field","<img src=\"http://dangjian.zf11.com/zf/17/vipzf21/UpLoadFiles/Article/2009-5/2009052215224031339.jpg\" border=0>",316,463);
$z[5][4]['name']="body";
$z[6]=Array("field","",465,505);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",507,546);
$z[7][4]['name']="litpic";

?>