{dede:field name='keywords'}心中有“家”甘奉献,真爱无私铸{/dede:field}
{dede:field name='description'}心中有“家”甘奉献 真爱无私铸警魂[暂无简介]{/dede:field}
{dede:field name='title'}心中有“家”甘奉献 真爱无私铸警魂{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<img src="http://dangjian.zf11.com/zf/17/vipzf21/UpLoadFiles/Article/2009-5/2009052215224031339.jpg" border=0>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
