{dede:field name='keywords'}佛山警方悬赏3000元追捕伤害致死{/dede:field}
{dede:field name='description'}佛山警方悬赏3000元追捕伤害致死案疑凶[暂无简介]{/dede:field}
{dede:field name='title'}佛山警方悬赏3000元追捕伤害致死案疑凶{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<P><FONT class=article>4月26日，佛山市南海公安分局丹灶派出所悬赏3000元追捕孙传清，孙传清是24日发生于丹灶的一宗伤害致死案的重大嫌疑人，警方已办理刑拘手续和上网追逃。</FONT></P><P><FONT class=article>&nbsp;&nbsp;&nbsp; 该派出所负责人介绍，孙传清，男，汉族，四川省隆昌县金鹅镇飞泉村人，身份证号码：511028196904091430，身高约170CM，身体中等，面部白净，有小胡须。凡提供线索抓获孙传清者，警方奖励3000元。丹灶派出所联系电话：（0757）85441540，85441066。</FONT></P><P><FONT class=article>&nbsp;&nbsp;&nbsp; 据调查，刘×荣和孙传清是同乡，均在丹灶西城村一种鸭场务工，4月24日中午11时左右，刘×荣该种鸭场内因工作关系与孙传清吵架，孙传清用弹簧刀捅刘×荣的右腹部两刀后逃跑，刘×荣经丹灶医院抢救无效死亡，孙传清有重大的作案嫌疑。（南公宣）</FONT></P>{/dede:field}
{dede:field name='litpic'}{/dede:field}
