{dede:field name='keywords'}李克强出席环境宏观战略座谈会并{/dede:field}
{dede:field name='description'}李克强出席环境宏观战略座谈会并发表重要讲话[暂无简介]{/dede:field}
{dede:field name='title'}李克强出席环境宏观战略座谈会并发表重要讲话{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<P><FONT face="Times New Roman">中共中央政治局常委、国务院副总理李克强２１日出席环境宏观战略座谈会时强调，要深入贯彻落实科学发展观，从战略上进一步加强环境保护，把生态环保作为保持经济平稳较快发展的重要举措，把节能减排作为调整经济结构的有效途径，努力实现清洁发展、节约发展、安全发展和可持续发展。</FONT></P><P><FONT face="Times New Roman">　　在听取环境宏观战略研究成果汇报和院士专家发言后，李克强说，当前我国经济发展正处于企稳回升的关键时期，也是结构调整的重要时期。要立足当前，着眼长远，保持政策的连续性和稳定性，提高政策的针对性、有效性和可持续性，把扩内需、保增长、调结构、惠民生有机结合起来，更加重视节能环保，加快经济结构调整步伐，大力发展绿色产业和循环经济，统筹城乡和区域环境保护，不断提高经济发展的质量效益和可持续发展能力。</FONT></P><P><FONT face="Times New Roman">　　李克强指出，近几年来，我国环境保护取得了积极进展，但环境形势依然严峻。随着经济增长和社会进步，环境保护是发展问题，也是民生问题。要坚持以人为本、优化发展，建设生态文明，保障环境安全，加大综合治理，强化法制建设，突出解决水、大气、土壤污染等环境问题，着力改善人民生活质量，让群众切实享受到环境改善带来的实惠。</FONT></P>{/dede:field}
{dede:field name='litpic'}{/dede:field}
