{dede:field name='keywords'}拉萨暴徒打砸区政府大楼,资讯,党{/dede:field}
{dede:field name='description'}拉萨暴徒打砸区政府大楼[暂无简介]{/dede:field}
{dede:field name='title'}拉萨暴徒打砸区政府大楼{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<P>&nbsp;</P><P><img src="/uploads/allimg/c111027/1319645E1520-35U6.jpg" border=0></P><P>赵峰是城关区政府一普通干部。当日上午，他跟往日一样来到单位上班。下午1点左右，赵峰在家里正准备吃饭，一阵急促的电话铃声突然响起，电话是值班室的同事打来的，告诉他远处传来阵阵叫喊声，天空烟云笼罩。 </P><P>　　<STRONG>暴徒纵火烧毁政法大楼</STRONG></P><P>　　赵峰感到情况不妙，放下饭菜，一路小跑来到值班室，马上向分管书记打电话汇报情况。在得到他的汇报后，分管领导马上向城关区所属的各乡、办事处紧急电话通知：要求所有临街的商铺关门，各乡、各办事处及区直各部门处于戒备状态。</P>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c111027/1319645E1520-35U6_lit.jpg{/dede:field}
