<?php
$z[0]=Array("field","广州市公安局悬赏通缉重大刑事案",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","广州市公安局悬赏通缉重大刑事案件在逃人员的公告[暂无简介]",73,173);
$z[1][4]['name']="description";
$z[2]=Array("field","广州市公安局悬赏通缉重大刑事案件在逃人员的公告",175,259);
$z[2][4]['name']="title";
$z[3]=Array("field","",261,300);
$z[3][4]['name']="writer";
$z[4]=Array("field","",302,341);
$z[4][4]['name']="source";
$z[5]=Array("field","",343,383);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<P align=left><FONT class=article>为进一步打击刑事犯罪活动，现对50名重大刑事案件在逃人员予以公开悬赏通缉。凡是直接扭送或提供线索成功抓获一名公开悬赏通缉在逃人员的，将由广州市公安局奖励举报人人民币3000元。广州市公安局将对举报人的身份采取严格的保密措施，并按举报人的意愿方式支付奖金。 </FONT></P><P align=left><FONT class=article>&nbsp;&nbsp;&nbsp; 广州市公安局举报电话：020-110 </FONT></P><P align=right><FONT class=article>广州市公安局</FONT></P>",385,868);
$z[6][4]['name']="body";
$z[7]=Array("field","",870,909);
$z[7][4]['name']="litpic";

?>