{dede:field name='keywords'}广州市公安局悬赏通缉重大刑事案{/dede:field}
{dede:field name='description'}广州市公安局悬赏通缉重大刑事案件在逃人员的公告[暂无简介]{/dede:field}
{dede:field name='title'}广州市公安局悬赏通缉重大刑事案件在逃人员的公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<P align=left><FONT class=article>为进一步打击刑事犯罪活动，现对50名重大刑事案件在逃人员予以公开悬赏通缉。凡是直接扭送或提供线索成功抓获一名公开悬赏通缉在逃人员的，将由广州市公安局奖励举报人人民币3000元。广州市公安局将对举报人的身份采取严格的保密措施，并按举报人的意愿方式支付奖金。 </FONT></P><P align=left><FONT class=article>&nbsp;&nbsp;&nbsp; 广州市公安局举报电话：020-110 </FONT></P><P align=right><FONT class=article>广州市公安局</FONT></P>{/dede:field}
{dede:field name='litpic'}{/dede:field}
