<?php
$z[0]=Array("field","中华人民共和国公安部令,公安网",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","中华人民共和国公安部令[暂无简介]",72,148);
$z[1][4]['name']="description";
$z[2]=Array("field","中华人民共和国公安部令",150,210);
$z[2][4]['name']="title";
$z[3]=Array("field","",212,251);
$z[3][4]['name']="writer";
$z[4]=Array("field","",253,292);
$z[4][4]['name']="source";
$z[5]=Array("field","",294,334);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<P><FONT class=article><BR>&nbsp;&nbsp;&nbsp; 修订后的《火灾事故调查规定》已经2009年4月30日公安部部长办公会议通过，现予发布，自2009年5月1日起施行。</FONT></P><P><FONT class=article></FONT>&nbsp;</P><P align=right><FONT class=article>公安部部长 孟建柱&nbsp;&nbsp;&nbsp; <BR>&nbsp;<BR>二○○九年四月三十日</FONT></P>",336,687);
$z[6][4]['name']="body";
$z[7]=Array("field","",689,728);
$z[7][4]['name']="litpic";

?>