{dede:field name='keywords'}中华人民共和国公安部令,公安网{/dede:field}
{dede:field name='description'}中华人民共和国公安部令[暂无简介]{/dede:field}
{dede:field name='title'}中华人民共和国公安部令{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<P><FONT class=article><BR>&nbsp;&nbsp;&nbsp; 修订后的《火灾事故调查规定》已经2009年4月30日公安部部长办公会议通过，现予发布，自2009年5月1日起施行。</FONT></P><P><FONT class=article></FONT>&nbsp;</P><P align=right><FONT class=article>公安部部长 孟建柱&nbsp;&nbsp;&nbsp; <BR>&nbsp;<BR>二○○九年四月三十日</FONT></P>{/dede:field}
{dede:field name='litpic'}{/dede:field}
