{dede:field name='keywords'}4部门夜查施工工地,仍有违规施工{/dede:field}
{dede:field name='description'}4部门夜查施工工地 仍有违规施工现象[暂无简介]{/dede:field}
{dede:field name='title'}4部门夜查施工工地 仍有违规施工现象{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}为保证高考生有一个安静的休息环境，6月4日晚，市城管局等4部门联合对全市工地进行突击检查。虽然大多数工地较好，但仍有一些工地在夜间违规施工。 <BR>　　6月4日晚10时许，市城管局联合市住房城乡建设委、市环保局、市教委等部门，分成5组对部分施工工地进行突击检查。在西城区真武庙二条，还未进入一家工地，就听到了机器的轰鸣声。执法人员刚进入工地，工人忙将刚刚还在运作的打料机关掉，但工地深处仍不断传来“叮叮当当”的敲击声。由于现场未见工地负责人，此事将交由当地城管分队负责处理。当晚检查中，大部分工地情况较好。 <BR>　　检查中，执法人员的手台不时传来举报工地夜间施工的情况。据执法人员介绍，自5月份以来，市民针对夜间施工扰民的举报居高不下，6月1日当天曾达到400件，比前一天上升50%。对此，市城管局等部门表示，随着高考的到来，有关部门将加强检查，并把考点及周边500米范围列入重点监控。<BR>{/dede:field}
{dede:field name='litpic'}{/dede:field}
