{dede:field name='keywords'}消防产品质量监督,公安网站,党建{/dede:field}
{dede:field name='description'}消防产品质量监督[暂无简介]{/dede:field}
{dede:field name='title'}消防产品质量监督{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<FONT class=article><STRONG>　一、消防产品准入程序 <BR><BR></STRONG>　　目前消防产品的准入实行强制性产品认证（ccc认证）、型式认可和强制检验三种制度，属于强制性产品认证和型式认可制度的产品，企业直接向公安部消防产品合格评定中心申请办证；对尚未列入强制性产品认证和型式认可制度范围，仍执行强制检验制度的产品，企业直接向有关消防产品检测机构申请抽封样品。<BR><BR>　　强制性产品认证和型式认可产品目录、申请书、办证程序、有关消防产品检测机构信息等可查询公安部消防产品合格评定中心网站（<A href="http://www.cccf.com.cn/">www.cccf.com.cn</A>&nbsp; 点击进入）。<BR><BR><STRONG>　　二、消防产品生产、进口、维修和销售环节监督程序<BR></STRONG><BR>　　对消防产品生产、进口、维修、销售单位的违法行为，由质量技术监督部门和出入境检验检疫机构负责监督，公安消防机构配合。<BR><BR><STRONG>　　三、消防产品使用环节监督程序<BR></STRONG><BR>　　1、审核准入条件<BR><BR>　　建筑工程验收时，公安消防机构审核其使用的消防产品是否符合消防产品准入条件。属于强制性产品认证的消防产品，须提供产品的强制性产品认证证书；属于型式认可的消防产品，须提供产品的型式认可证书；属于强制检验的消防产品，须提供产品检测周期内的型式检验报告。<BR><BR>公安消防机构可对消防产品在施工安装前进行抽查，必要时可对主要的、大批量的消防产品进行抽样检验。<BR><BR>　　2、使用环节违法行为的监督<BR><BR>　　对使用单位的违法行为，由公安消防机构依据消防法的有关规定进行处罚；对违法产品，应采取责令停止使用、发布公告等行政处置措施，并提请质量技术监督部门或出入境检验检疫机构对涉嫌违法的生产、进口、维修、销售单位进行处罚，同时将处罚结果通知消防产品认证机构。</FONT>{/dede:field}
{dede:field name='litpic'}{/dede:field}
