{dede:field name='keywords'}正规照相部开业 黑照相基本绝迹,{/dede:field}
{dede:field name='description'}正规照相部开业 黑照相基本绝迹[暂无简介]{/dede:field}
{dede:field name='title'}正规照相部开业　黑照相基本绝迹{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<TABLE cellSpacing=0 cellPadding=0 width=800 bgColor=#ffffff border=0><TBODY><TR><TD class=hig175 vAlign=top align=left><P>颐和园东门外的“黑照相”一直屡禁不绝，因照片质量和收费问题引起的纠纷屡屡发生。昨天记者发现，在海淀城管青龙桥分队和颐和园管理处共同努力下开设的正规颐和园照相部让“黑照相”基本绝迹。<BR>　　昨天上午，记者来到颐和园东门外，在广场西南侧看到了设置的颐和园照相部，而常常出现在东门周边的“黑照相”没了踪影。<BR>　　海淀城管青龙桥分队的队员说，他们经常会接到游客对于颐和园门口“黑照相”的投诉。城管人员在巡查中发现，东门外没有正规的照相部，于是“黑照相”占领了这一商机。<BR>　　在海淀城管青龙桥分队的协调下，5月上旬，由颐和园管理处设置在东门外广场西南侧的颐和园照相部正式开始营业。据了解，开业以来，每天约有近百名游客在此拍照留念。照相部在满足游客需求的同时，“黑照相”引起的游客投诉问题也得到了解决。<BR></P></TD><TD vAlign=top>&nbsp;</TD></TR></TBODY></TABLE>{/dede:field}
{dede:field name='litpic'}{/dede:field}
