{dede:field name='keywords'}无悔的选择,公安网站,党建网站模{/dede:field}
{dede:field name='description'}无悔的选择[暂无简介]{/dede:field}
{dede:field name='title'}无悔的选择{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<img src="http://dangjian.zf11.com/zf/17/vipzf21/UpLoadFiles/Article/2009-5/2009052215241064419.jpg" border=0>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
