<?php
$z[0]=Array("field","无悔的选择,公安网站,党建网站模",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","无悔的选择[暂无简介]",73,137);
$z[1][4]['name']="description";
$z[2]=Array("field","无悔的选择",139,187);
$z[2][4]['name']="title";
$z[3]=Array("field","",189,228);
$z[3][4]['name']="writer";
$z[4]=Array("field","",230,269);
$z[4][4]['name']="source";
$z[5]=Array("field","<img src=\"http://dangjian.zf11.com/zf/17/vipzf21/UpLoadFiles/Article/2009-5/2009052215241064419.jpg\" border=0>",271,418);
$z[5][4]['name']="body";
$z[6]=Array("field","",420,460);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",462,501);
$z[7][4]['name']="litpic";

?>