{dede:field name='keywords'}温家宝出席第十一次驻外使节会议{/dede:field}
{dede:field name='description'}温家宝出席第十一次驻外使节会议并讲话[暂无简介]{/dede:field}
{dede:field name='title'}温家宝出席第十一次驻外使节会议并讲话{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<P><FONT face="Times New Roman">温家宝出席第十一次驻外使节会议并讲话</FONT></P><P><FONT face="Times New Roman">全国最专业的党建网站、组织部网站、党建网站建设中心、组织部网站建设中心、专业提供党建网站设计、专业提供组织部网站设计、党建网站模板、组织部网站模板、党建网站源码、组织部网站源码、党建网站管理系统、组织部网站管理系统、党建网站建设方案、组织部网站建设方案</FONT></P>{/dede:field}
{dede:field name='litpic'}{/dede:field}
