<?php
$z[0]=Array("field","温家宝出席第十一次驻外使节会议",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","温家宝出席第十一次驻外使节会议并讲话[暂无简介]",73,163);
$z[1][4]['name']="description";
$z[2]=Array("field","温家宝出席第十一次驻外使节会议并讲话",165,239);
$z[2][4]['name']="title";
$z[3]=Array("field","",241,280);
$z[3][4]['name']="writer";
$z[4]=Array("field","",282,321);
$z[4][4]['name']="source";
$z[5]=Array("field","",323,363);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<P><FONT face=\"Times New Roman\">温家宝出席第十一次驻外使节会议并讲话</FONT></P><P><FONT face=\"Times New Roman\">全国最专业的党建网站、组织部网站、党建网站建设中心、组织部网站建设中心、专业提供党建网站设计、专业提供组织部网站设计、党建网站模板、组织部网站模板、党建网站源码、组织部网站源码、党建网站管理系统、组织部网站管理系统、党建网站建设方案、组织部网站建设方案</FONT></P>",365,776);
$z[6][4]['name']="body";
$z[7]=Array("field","",778,817);
$z[7][4]['name']="litpic";

?>