<?php
$z[0]=Array("global","",180,209);
$z[0][4]['name']="cfg_templeturl";
$z[1]=Array("field","",335,363);
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",365,394);
$z[2][4]['name']="typename";
$z[3]=Array("field","",454,482);
$z[3][4]['name']="typeurl";
$z[4]=Array("global","",494,523);
$z[4][4]['name']="cfg_templeturl";
$z[5]=Array("arclist","	\r\n<tr><td align=\"left\" class=\"line-i\">&nbsp;<img src=\"[field:global.cfg_templeturl/]/skin/images/ico.gif\"/>&nbsp;<a href=\"[field:arcurl/]\" title=\"标题：[field:fulltitle function='html2text(@me)'/]\r\n更新：[field:pubdate function='GetDateTimeMK(@me)'/]\" target=\"_blank\" onClick=\"return newpage(this.href);\">[field:title /]</a></td>\r\n<td align=\"right\"><font color=\"#999999\">[</font><font color=\"#999999\">[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</font><font color=\"#999999\">]</font></td></tr>\r\n",1014,1560);
$z[5][4]['row']="7";
$z[5][4]['titlelen']="52";

?>