<?php
$z[0]=Array("field","奥运火炬伊斯坦布尔传递,塔克希",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","奥运火炬伊斯坦布尔传递 塔克希姆广场圣火盆[暂无简介]",72,167);
$z[1][4]['name']="description";
$z[2]=Array("field","奥运火炬伊斯坦布尔传递 塔克希姆广场圣火盆",169,248);
$z[2][4]['name']="title";
$z[3]=Array("field","",250,289);
$z[3][4]['name']="writer";
$z[4]=Array("field","",291,330);
$z[4][4]['name']="source";
$z[5]=Array("field","",332,372);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<P><img src=\"/uploads/allimg/c111027/1319645F1I0-56113.jpg\" border=0></P><P><BR>&lt;--IMG END--&gt;</P><P>　　4月3日，在圣火传递终点――塔克希姆广场，护火手展示火种灯。当日，<A class=akey href=\"http://2008.sina.com.cn/\" target=_blank>北京奥运会</A>圣火境外传递第二站在土耳其伊斯坦布尔结束。</P><P>　　新华社记者周文杰摄</P><P>&lt;--正文内容结束--&gt;&lt;--关于内容的操作开始--&gt;&lt;--发表评论开始--&gt;</P>",374,819);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c111027/1319645F1I0-56113_lit.jpg",821,909);
$z[7][4]['name']="litpic";

?>