{dede:field name='keywords'}奥运火炬伊斯坦布尔传递,塔克希{/dede:field}
{dede:field name='description'}奥运火炬伊斯坦布尔传递 塔克希姆广场圣火盆[暂无简介]{/dede:field}
{dede:field name='title'}奥运火炬伊斯坦布尔传递 塔克希姆广场圣火盆{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<P><img src="/uploads/allimg/c111027/1319645F1I0-56113.jpg" border=0></P><P><BR>&lt;--IMG END--&gt;</P><P>　　4月3日，在圣火传递终点――塔克希姆广场，护火手展示火种灯。当日，<A class=akey href="http://2008.sina.com.cn/" target=_blank>北京奥运会</A>圣火境外传递第二站在土耳其伊斯坦布尔结束。</P><P>　　新华社记者周文杰摄</P><P>&lt;--正文内容结束--&gt;&lt;--关于内容的操作开始--&gt;&lt;--发表评论开始--&gt;</P>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c111027/1319645F1I0-56113_lit.jpg{/dede:field}
