<?php
$z[0]=Array("field","办理液化石油气供应站消防审核与",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","办理液化石油气供应站消防审核与验收指引[暂无简介]",73,165);
$z[1][4]['name']="description";
$z[2]=Array("field","办理液化石油气供应站消防审核与验收指引",167,243);
$z[2][4]['name']="title";
$z[3]=Array("field","",245,284);
$z[3][4]['name']="writer";
$z[4]=Array("field","",286,325);
$z[4][4]['name']="source";
$z[5]=Array("field","",327,367);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<P><FONT class=article><STRONG>办理液化石油气供应站消防审核指引</STRONG></FONT></P><P><FONT class=article>&nbsp;&nbsp;&nbsp; 1、建设单位出具的申请函；<BR>&nbsp;&nbsp;&nbsp; 2、建筑工程消防设计防火审核申报表；<BR>&nbsp;&nbsp;&nbsp; 3、建筑图（蓝图）一套，包括；四至图（表明周围25范围内建筑情况）、平面图、电气线路图；<BR>&nbsp;&nbsp;&nbsp; 4、市政园林局选址批文。<BR>&nbsp;<BR>&nbsp;&nbsp;&nbsp; <STRONG>办理液化石油气供应站消防验收指引<BR></STRONG>&nbsp;<BR>&nbsp;&nbsp;&nbsp; 1、建设单位出具的申请函；<BR>&nbsp;&nbsp;&nbsp; 2、建筑工程消防设计防火审核申报表；<BR>&nbsp;&nbsp;&nbsp; 3、建筑竣工图；<BR>&nbsp;&nbsp;&nbsp; 4、消防产品检测报告。<BR>&nbsp;<BR><STRONG>注：</STRONG>1、报建手续应由建设单位办理。</FONT></P>",369,1123);
$z[6][4]['name']="body";
$z[7]=Array("field","",1125,1164);
$z[7][4]['name']="litpic";

?>