{dede:field name='keywords'}办理液化石油气供应站消防审核与{/dede:field}
{dede:field name='description'}办理液化石油气供应站消防审核与验收指引[暂无简介]{/dede:field}
{dede:field name='title'}办理液化石油气供应站消防审核与验收指引{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<P><FONT class=article><STRONG>办理液化石油气供应站消防审核指引</STRONG></FONT></P><P><FONT class=article>&nbsp;&nbsp;&nbsp; 1、建设单位出具的申请函；<BR>&nbsp;&nbsp;&nbsp; 2、建筑工程消防设计防火审核申报表；<BR>&nbsp;&nbsp;&nbsp; 3、建筑图（蓝图）一套，包括；四至图（表明周围25范围内建筑情况）、平面图、电气线路图；<BR>&nbsp;&nbsp;&nbsp; 4、市政园林局选址批文。<BR>&nbsp;<BR>&nbsp;&nbsp;&nbsp; <STRONG>办理液化石油气供应站消防验收指引<BR></STRONG>&nbsp;<BR>&nbsp;&nbsp;&nbsp; 1、建设单位出具的申请函；<BR>&nbsp;&nbsp;&nbsp; 2、建筑工程消防设计防火审核申报表；<BR>&nbsp;&nbsp;&nbsp; 3、建筑竣工图；<BR>&nbsp;&nbsp;&nbsp; 4、消防产品检测报告。<BR>&nbsp;<BR><STRONG>注：</STRONG>1、报建手续应由建设单位办理。</FONT></P>{/dede:field}
{dede:field name='litpic'}{/dede:field}
