{dede:field name='keywords'}交通运输部召开深入学习实践科学{/dede:field}
{dede:field name='description'}交通运输部召开深入学习实践科学发展观活动总结大会[暂无简介]{/dede:field}
{dede:field name='title'}交通运输部召开深入学习实践科学发展观活动总结大会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}2月26日上午，交通运输部召开深入学习实践科学发展观活动总结大会。交通运输部党组书记、部长、部学习实践活动领导小组组长李盛霖全面总结了学习实践活动的做法、特点和成效，并对下一步工作提出要求。全国政协常委、中央统战部原常务副部长梁金泉率中央第18指导检查组全体同志出席会议并讲话。会议由部党组副书记、副部长、部学习实践活动领导小组副组长翁孟勇主持。部党组成员、副部长、部学习实践活动领导小组成员高宏峰、徐祖远和部党组成员、驻部纪检组组长、部学习实践活动领导小组成员兼办公室主任杨利民，离退休部领导出席会议。图为李盛霖部长在总结大会上作重要讲话。{/dede:field}
{dede:field name='litpic'}{/dede:field}
