{dede:field name='keywords'}青少年暴力事件缘何屡屡发生,公{/dede:field}
{dede:field name='description'}青少年暴力事件缘何屡屡发生[暂无简介]{/dede:field}
{dede:field name='title'}青少年暴力事件缘何屡屡发生{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<FONT class=article>&nbsp; 有关教育专家指出，要尽早察觉有潜在危机的青少年，减少他们违法犯罪的可能性。什么样的人是有潜在危机的对象呢？科学研究和司法实践经验的总结指出，那些自我形象低（自卑感重）、逆反心理强、容易受不良影响而拉帮结伙、学习成绩又欠佳的未成年人，应特别关心他们。最重要的是家人和老师都不可嫌弃他们，而要抱着接纳的态度。接纳是首要的，千万别流露出不屑的眼神和口气，这样便可增加对他们的吸引力，而减少违规、违法人员对他们的吸引力，使他们在正确与错误、守法与违法的十字路口上走向正确、守法的道路。</FONT>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
