<table width="100%" cellpadding="0" cellspacing="0" border="0" align="center"><tr valign="top"><td align="center"  class="line-i" ><a href="[field:arcurl/]" title="标题：[field:fulltitle function='html2text(@me)'/]
作者：[field:writer /]
更新：[field:pubdate function='GetDateTimeMK(@me)'/]
点击：[field:click/]" target="_blank"><img src="[field:litpic/]" width="290" height="226" border="0"  alt="" /></a>
<div style="text-indent:20px;text-align:left;line-height:22px;padding-top:6px;"><a href="[field:arcurl/]" > &nbsp; [field:info/]……</a></div></td></tr></table>