{dede:field name='keywords'}恶徒武汉作案 广东警方悬赏缉凶,{/dede:field}
{dede:field name='description'}恶徒武汉作案 广东警方悬赏缉凶[暂无简介]{/dede:field}
{dede:field name='title'}恶徒武汉作案 广东警方悬赏缉凶{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<FONT class=article>&nbsp; 广东省公安厅近日转发公安部通缉令，要求各地公安机关协助湖北省武汉市警方追捕一起重大杀人案的犯罪嫌疑人张伟。 </FONT><P><FONT class=article>&nbsp;&nbsp;&nbsp; 2004年7月22日，武汉市发生一起重大杀人案，犯罪嫌疑人张伟杀死二人后潜逃。 </FONT></P><P><FONT class=article>&nbsp;&nbsp;&nbsp; 张伟又名凌伟，男，汉族，1977年6月7日出生，系河南省信阳市师河区李家寨镇老门村人，身高1.70米左右，圆脸，平头，体态偏瘦，河南口音，讲话有时吐字不清，身份证号为413023197706077313。出逃时可能持有假身份证。 </FONT></P><P><FONT class=article>&nbsp;&nbsp;&nbsp; 据了解，张伟作案后有企图逃往境外的可能，请广大群众积极提供线索，协助公安机关抓捕犯罪嫌疑人，对提供线索抓获犯罪嫌疑人的单位或个人，公安机关将给予人民币2万元奖励。 </FONT></P><P><FONT class=article>&nbsp;&nbsp;&nbsp; 举报电话，当地公安机关110或广东省公安厅刑侦局020-83110906。 （肖定东） </FONT></P>{/dede:field}
{dede:field name='litpic'}{/dede:field}
