{dede:field name='keywords'}奥运圣火在伊斯坦布尔传递,美少{/dede:field}
{dede:field name='description'}奥运圣火在伊斯坦布尔传递 美少女迷人微笑[暂无简介]{/dede:field}
{dede:field name='title'}奥运圣火在伊斯坦布尔传递 美少女迷人微笑{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<P><img src="/uploads/allimg/c111027/1319645G2R0-2I38.jpg" border=0></P><P>4月3日，土耳其第一棒火炬手图巴·卡拉狄米尔(左)与土耳其奥委会主席托艾·巴亚特利一起展示<A class=akey href="http://2008.sina.com.cn/" target=_blank>北京奥运会</A>火炬。当日，北京奥运会圣火传递活动在土耳其伊斯坦布尔进行，这是北京奥运会圣火境外传递第二站。 </P><P>　　新华社记者郭磊摄</P>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c111027/1319645G2R0-2I38_lit.jpg{/dede:field}
