<?php
$z[0]=Array("field","奥运圣火在伊斯坦布尔传递,美少",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","奥运圣火在伊斯坦布尔传递 美少女迷人微笑[暂无简介]",72,165);
$z[1][4]['name']="description";
$z[2]=Array("field","奥运圣火在伊斯坦布尔传递 美少女迷人微笑",167,244);
$z[2][4]['name']="title";
$z[3]=Array("field","",246,285);
$z[3][4]['name']="writer";
$z[4]=Array("field","",287,326);
$z[4][4]['name']="source";
$z[5]=Array("field","",328,368);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<P><img src=\"/uploads/allimg/c111027/1319645G2R0-2I38.jpg\" border=0></P><P>4月3日，土耳其第一棒火炬手图巴·卡拉狄米尔(左)与土耳其奥委会主席托艾·巴亚特利一起展示<A class=akey href=\"http://2008.sina.com.cn/\" target=_blank>北京奥运会</A>火炬。当日，北京奥运会圣火传递活动在土耳其伊斯坦布尔进行，这是北京奥运会圣火境外传递第二站。 </P><P>　　新华社记者郭磊摄</P>",370,766);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c111027/1319645G2R0-2I38_lit.jpg",768,855);
$z[7][4]['name']="litpic";

?>