{dede:field name='keywords'}胡锦涛等党和国家领导同志亲切接{/dede:field}
{dede:field name='description'}胡锦涛等党和国家领导同志亲切接见了会议代表[暂无简介]{/dede:field}
{dede:field name='title'}胡锦涛等党和国家领导同志亲切接见了会议代表{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<FONT id=Zoom>&nbsp;出席今天大会的党和国家领导同志有：中共中央政治局委员、国务院副总理、国务院残工委主任回良玉同志；中共中央政治局委员、国务委员刘延东同志；中共中央政治局委员、中央军委副主席徐才厚同志；全国人大常委会副委员长华建敏同志；全国政协副主席张梅颖同志；全国政协副主席、国务院残工委副主任、中国残联名誉主席邓朴方同志。</FONT>{/dede:field}
{dede:field name='litpic'}{/dede:field}
