{dede:specnote imgheight='90' imgwidth='120'
                infolen='160' titlelen='60' col='1' idlist='135,134,133,132,131,130,129,128,127,126,125,124,123,122,121,120,119,118,117,116,115,114,113,112,111,110,109,108,107,106'
                name='默认节点' noteid='default' isauto='0' rownum='20'
                keywords='' typeid='0'}
                <tr><td align="left"  class="line-i">&nbsp;<img src="[field:global.cfg_templeturl/]/skin/images/ico.gif"/>&nbsp;<a href="[field:arcurl/]" title="标题：[field:fulltitle function='html2text(@me)'/]
作者：[field:writer /]
更新：[field:pubdate function='GetDateTimeMK(@me)'/]
点击：[field:click/]" target="_blank">[field:title/]</a></td>
<td align="right"  class="line-i"><font color="#999999">[[field:pubdate function="MyDate('Y-m-d',@me)"/]]</font></td></tr>
                {/dede:specnote}
