<?php
$z[0]=Array("specnote","\r\n                <tr><td align=\"left\"  class=\"line-i\">&nbsp;<img src=\"[field:global.cfg_templeturl/]/skin/images/ico.gif\"/>&nbsp;<a href=\"[field:arcurl/]\" title=\"标题：[field:fulltitle function='html2text(@me)'/]\r\n作者：[field:writer /]\r\n更新：[field:pubdate function='GetDateTimeMK(@me)'/]\r\n点击：[field:click/]\" target=\"_blank\">[field:title/]</a></td>\r\n<td align=\"right\"  class=\"line-i\"><font color=\"#999999\">[[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]]</font></td></tr>\r\n                ",0,852);
$z[0][4]['imgheight']="90";
$z[0][4]['imgwidth']="120";
$z[0][4]['infolen']="160";
$z[0][4]['titlelen']="60";
$z[0][4]['col']="1";
$z[0][4]['idlist']="135,134,133,132,131,130,129,128,127,126,125,124,123,122,121,120,119,118,117,116,115,114,113,112,111,110,109,108,107,106";
$z[0][4]['name']="默认节点";
$z[0][4]['noteid']="default";
$z[0][4]['isauto']="0";
$z[0][4]['rownum']="20";
$z[0][4]['keywords']="";
$z[0][4]['typeid']="0";

?>