<?php
$z[0]=Array("typeurl","",105,121);
$z[1]=Array("typename","",123,141);
$z[2]=Array("arcurl","",168,184);
$z[3]=Array("fulltitle","",199,243);
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("writer","",251,267);
$z[5]=Array("pubdate","",275,321);
$z[5][4]['function']="GetDateTimeMK(@me)";
$z[6]=Array("click","",329,343);
$z[7]=Array("title","",361,376);
$z[8]=Array("pubdate","",476,523);
$z[8][4]['function']="MyDate('Y-m-d',@me)";

?>