{dede:field name='keywords'}国际刑警组织对香港大毒枭钟坤成{/dede:field}
{dede:field name='description'}国际刑警组织对香港大毒枭钟坤成发布红色通缉令[暂无简介]{/dede:field}
{dede:field name='title'}国际刑警组织对香港大毒枭钟坤成发布红色通缉令{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<FONT class=article><P>经广东省公安厅查明：犯罪嫌疑人钟坤成，于1999年至2003年间，伙同犯罪嫌疑人陈森、谢伟明等人用化学合成的方法在广东省广州市、惠州市、河南省驻马店等地大肆制造冰毒予以贩卖，其中被我省公安机关缴获的冰毒4吨多。同时，犯罪嫌疑人钟坤成还涉嫌多宗走私、贩卖海洛因重特大案件。犯罪嫌疑人钟坤成的行为已触犯了《中华人民共和国刑法》第三百四十七条之规定，涉嫌制造、贩卖毒品罪。犯罪嫌疑人钟坤成一直负案在逃，长期藏匿在香港等地。2008年5月8 日，经广东省人民检察院批准，决定逮捕犯罪嫌疑人钟坤成。最近，广东省公安厅通过国际刑警组织中国国家中心局向全球发布对犯罪嫌疑人钟坤成的红色通缉令。</P><P>&nbsp;&nbsp;&nbsp; 犯罪嫌疑人钟坤成，英文名：Chung Kwan Shing, 曾用名钟坤松，绰号：歪嘴成，男，1956年09月15日生，身高174厘米，体重75公斤，黑头发，黑眼睛，香港身份证号码：H007305，香港护照号码：HA9106756。（陈奕浩 夏晓露 编辑：刘阳）</P></FONT>{/dede:field}
{dede:field name='litpic'}{/dede:field}
