{dede:field name='keywords'}民航总局称东航返航飞行员不会遭{/dede:field}
{dede:field name='description'}民航总局称东航返航飞行员不会遭终身禁飞处罚[暂无简介]{/dede:field}
{dede:field name='title'}民航总局称东航返航飞行员不会遭终身禁飞处罚{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<P><img src="/uploads/allimg/c111027/1319645D6030-25255.jpg" border=0></P><P>&nbsp;</P>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c111027/1319645D6030-25255_lit.jpg{/dede:field}
