<?php
$z[0]=Array("field","民航总局称东航返航飞行员不会遭",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","民航总局称东航返航飞行员不会遭终身禁飞处罚[暂无简介]",73,169);
$z[1][4]['name']="description";
$z[2]=Array("field","民航总局称东航返航飞行员不会遭终身禁飞处罚",171,251);
$z[2][4]['name']="title";
$z[3]=Array("field","",253,292);
$z[3][4]['name']="writer";
$z[4]=Array("field","",294,333);
$z[4][4]['name']="source";
$z[5]=Array("field","",335,375);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<P><img src=\"/uploads/allimg/c111027/1319645D6030-25255.jpg\" border=0></P><P>&nbsp;</P>",377,501);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c111027/1319645D6030-25255_lit.jpg",503,592);
$z[7][4]['name']="litpic";

?>