<?php
$z[0]=Array("global","",323,352);
$z[0][4]['name']="cfg_templeturl";
$z[1]=Array("global","",572,601);
$z[1][4]['name']="cfg_templeturl";
$z[2]=Array("arclist","\r\n<tr><td align=\"left\"  class=\"line-i\">&nbsp;<a href=\"[field:arcurl/]\"\r\n  title=\"标题：[field:fulltitle function='html2text(@me)'/]\r\n作者：[field:writer /]\r\n更新：[field:pubdate function='GetDateTimeMK(@me)'/]\r\n点击：[field:click/]\" target=\"_blank\">[field:title/]</a></td></tr>\r\n      ",739,1101);
$z[2][4]['row']="10";
$z[2][4]['orderby']="click";
$z[2][4]['titlelen']="40";
$z[2][4]['typeid']="all";
$z[3]=Array("global","",1171,1200);
$z[3][4]['name']="cfg_templeturl";

?>