<div class="topTitle">
				<table width="100%" border="0" cellpadding="0" cellspacing="0" class="line-i">
					<tr><td align="left"  class="line-i">&nbsp;<a href="[field:arcurl /]" title="标题：[field:fulltitle function='html2text(@me)'/]
						作者：[field:writer /]
						更新：[field:pubdate function='GetDateTimeMK(@me)'/]
						点击：[field:click/]" target="_blank">[field:title /]</a></td></tr>
					</table></div>