<?php
$z[0]=Array("global","@me=@me-1;",22,89);
$z[0][4]['name']="autoindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",92,107);
$z[2]=Array("global","@me=@me-1;",129,196);
$z[2][4]['name']="autoindex";
$z[2][4]['runphp']="yes";
$z[3]=Array("litpic","",199,214);
$z[4]=Array("global","@me=@me-1;",241,308);
$z[4][4]['name']="autoindex";
$z[4][4]['runphp']="yes";
$z[5]=Array("title","",311,351);
$z[5][4]['function']="html2text(@me)";

?>