<tr>
        <td height="30" class="newsTitle2"><table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td width="33" align="left"><img src="{dede:global.cfg_templeturl/}/skin/images/title_ico1.gif" width="26" height="30" /></td>
            <td width="426" align="left" class="yjnews"><a href="{dede:field name='typeurl'/}">{dede:field name='typename'/}</a></td>
            <td width="87" align="left"><a href="{dede:field name='typeurl'/}"><img src="{dede:global.cfg_templeturl/}/skin/images/more2.gif" width="56" height="11" border="0" /></a></td>
          </tr>
        </table></td>
      </tr>
      <tr>
        <td align="left" valign="top"><div class="newst"><!--栏目循环（1）-->
<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">
    <tr>
    	<tr> 
	<td><table width="100%" border="0" cellpadding="0" cellspacing="0">
		<tr> 
		<td height="150" valign="top">
			<table width="100%" border="0" cellpadding="0" cellspacing="0"  class="line-i">
<tr><td align="left" class="line-i">&nbsp;<img src="{dede:global.cfg_templeturl/}/skin/images/ico.gif" alt="普通" />&nbsp;<a href="/zf/Movie/sptv/ldtv/1520090722145835.html" title="标题：领导干部要不断提高能力素质切实改进作风更好地担负起领导部队建设科学发展的重任
点击：2009-7-22 14:58:35" target="_blank" onClick="return newpage(this.href);">领导干部要不断提高能力素质切实改进作风更...</a></td>
<td align="right"><font color="#999999">[</font><font color="#999999">2009-07-22</font><font color="#999999">]</font></td></tr>
<tr><td align="left" class="line-i">&nbsp;<img src="{dede:global.cfg_templeturl/}/skin/images/ico.gif" alt="普通" />&nbsp;<a href="/zf/Movie/sptv/ldtv/1420090722145651.html" title="标题：贾庆林13日在京会见巴基斯坦参议院主席奈克
点击：2009-7-22 14:56:51" target="_blank" onClick="return newpage(this.href);">贾庆林13日在京会见巴基斯坦参议院主席奈克...</a></td>
<td align="right"><font color="#999999">[</font><font color="#999999">2009-07-22</font><font color="#999999">]</font></td></tr>
<tr><td align="left" class="line-i">&nbsp;<img src="{dede:global.cfg_templeturl/}/skin/images/ico.gif" alt="普通" />&nbsp;<a href="/zf/Movie/sptv/ldtv/1320090722145530.html" title="标题：吴邦国在人民大会堂会见巴基斯坦参议院主席奈克
点击：2009-7-22 14:55:30" target="_blank" onClick="return newpage(this.href);">吴邦国在人民大会堂会见巴基斯坦参议院主席...</a></td>
<td align="right"><font color="#999999">[</font><font color="#999999">2009-07-22</font><font color="#999999">]</font></td></tr>
<tr><td align="left" class="line-i">&nbsp;<img src="{dede:global.cfg_templeturl/}/skin/images/ico.gif" alt="普通" />&nbsp;<a href="/zf/Movie/sptv/ldtv/1220090722145404.html" title="标题：孟建柱:加强群防群治建设 构筑打击犯罪天罗地网
点击：2009-7-22 14:54:04" target="_blank" onClick="return newpage(this.href);">孟建柱:加强群防群治建设 构筑打击犯罪天罗...</a></td>
<td align="right"><font color="#999999">[</font><font color="#999999">2009-07-22</font><font color="#999999">]</font></td></tr>
<tr><td align="left" class="line-i">&nbsp;<img src="{dede:global.cfg_templeturl/}/skin/images/ico.gif" alt="普通" />&nbsp;<a href="/zf/Movie/sptv/ldtv/1120090722145233.html" title="标题：周永康15日上午在人民大会堂会见苏丹国防部长
点击：2009-7-22 14:52:33" target="_blank" onClick="return newpage(this.href);">周永康15日上午在人民大会堂会见苏丹国防部...</a></td>
<td align="right"><font color="#999999">[</font><font color="#999999">2009-07-22</font><font color="#999999">]</font></td></tr>
<tr><td align="left" class="line-i">&nbsp;<img src="{dede:global.cfg_templeturl/}/skin/images/ico.gif" alt="普通" />&nbsp;<a href="/zf/Movie/sptv/ldtv/1020090722145053.html" title="标题：李克强在中南海紫光阁会见泰国国防部长巴维一行
点击：2009-7-22 14:50:53" target="_blank" onClick="return newpage(this.href);">李克强在中南海紫光阁会见泰国国防部长巴维...</a></td>
<td align="right"><font color="#999999">[</font><font color="#999999">2009-07-22</font><font color="#999999">]</font></td></tr>
<tr><td align="left" class="line-i">&nbsp;<img src="{dede:global.cfg_templeturl/}/skin/images/ico.gif" alt="普通" />&nbsp;<a href="/zf/Movie/sptv/ldtv/920090722144709.html" title="标题：刘延东出席中美清洁能源联合研究中心成立发布会
点击：2009-7-22 14:47:09" target="_blank" onClick="return newpage(this.href);">刘延东出席中美清洁能源联合研究中心成立发...</a></td>
<td align="right"><font color="#999999">[</font><font color="#999999">2009-07-22</font><font color="#999999">]</font></td></tr>
</table>
		</td>
		</tr>
	</table></td>
	</tr>
</table></td>
<!--栏目循环（4）-->
</tr><tr><td colspan="3" align="center" height="5"></td></tr><tr>
    </tr>
</table></div></td>
      </tr>