<?php
$z[0]=Array("field","",37,66);
$z[0][4]['name']="typename";
$z[1]=Array("arclist","\r\n				<tr><td align=\"left\"  class=\"line-i\">&nbsp;<img src=\"[field:global.cfg_templeturl/]/skin/images/ico.gif\"/>&nbsp;<a href=\"[field:arcurl /]\" title=\"标题：[field:fulltitle function='html2text(@me)'/]作者：[field:writer /]更新：[field:pubdate function='GetDateTimeMK(@me)'/]点击：[field:click/]\" target=\"_blank\">[field:title /]</a></td></tr>\r\n			    ",285,688);
$z[1][4]['titlelen']="26";
$z[1][4]['row']="8";

?>