{dede:field name='keywords'}交通运输部召开党组分析检查报告{/dede:field}
{dede:field name='description'}交通运输部召开党组分析检查报告群众评议大会[暂无简介]{/dede:field}
{dede:field name='title'}交通运输部召开党组分析检查报告群众评议大会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}交通运输部党组召开党组分析检查报告群众评议大会，部党组书记、部长、部学习实践活动领导小组组长李盛霖就部党组贯彻落实科学发展观分析检查报告起草过程以及主要内容作了说明，并对群众评议工作进行部署。部党组副书记、副部长、部学习实践活动领导小组副组长翁孟勇主持会议，并对开展好群众评议活动提出要求。部党组成员、副部长、部学习实践活动领导小组成员高宏峰、徐祖远，部党组成员、驻部纪检组组长、部学习实践活动领导小组成员兼办公室主任杨利民参加大会。中央学习实践活动第18指导检查组组长梁金泉、副组长徐学海出席会议。部机关司局级干部和处级领导干部、离退休干部党支部书记、部属在京各单位领导班子成员参加会议。图为会议现场。{/dede:field}
{dede:field name='litpic'}{/dede:field}
