<?php
$z[0]=Array("sppage","",0,73);
$z[0][4]['sptype']="full";
$z[0][4]['srul']="1";
$z[0][4]['erul']="5";
$z[1]=Array("previewurl","http://dangjian.zf11.com/zf/Article/281.html",75,154);
$z[2]=Array("keywordtrim","",156,193);
$z[3]=Array("descriptiontrim","",195,240);
$z[4]=Array("item","\r\n   {dede:match}<td align=\"center\" valign=\"middle\"><h1>[ÄÚÈÝ]</h1></td>{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",242,436);
$z[4][4]['field']="title";
$z[4][4]['value']="";
$z[4][4]['isunit']="";
$z[4][4]['isdown']="";
$z[5]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",438,578);
$z[5][4]['field']="writer";
$z[5][4]['value']="";
$z[5][4]['isunit']="";
$z[5][4]['isdown']="";
$z[6]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",580,720);
$z[6][4]['field']="source";
$z[6][4]['value']="";
$z[6][4]['isunit']="";
$z[6][4]['isdown']="";
$z[7]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}@me=GetMkTime(@me);{/dede:function}\r\n",722,882);
$z[7][4]['field']="pubdate";
$z[7][4]['value']="";
$z[7][4]['isunit']="";
$z[7][4]['isdown']="";
$z[8]=Array("item","\r\n   {dede:match}<td valign=\"top\" id=\"ArticleBody\"  align=\"left\">[ÄÚÈÝ]</td>\r\n              </tr>\r\n            </table></td></tr>{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",884,1136);
$z[8][4]['field']="body";
$z[8][4]['value']="";
$z[8][4]['isunit']="1";
$z[8][4]['isdown']="1";

?>