<?php
$z[0]=Array("noteinfo","",0,160);
$z[0][4]['notename']="ĞÂÎÅ";
$z[0][4]['channelid']="1";
$z[0][4]['macthtype']="string";
$z[0][4]['refurl']="http://";
$z[0][4]['sourcelang']="gb2312";
$z[0][4]['cosort']="asc";
$z[0][4]['isref']="no";
$z[0][4]['exptime']="10";
$z[0][4]['usemore']="0";
$z[1]=Array("listrule","\r\n    {dede:addurls}http://dangjian.zf11.com/Article/ShowClass.asp?ClassID=3{/dede:addurls}\r\n    {dede:batchrule}{/dede:batchrule}\r\n    {dede:regxrule}{/dede:regxrule}\r\n    {dede:areastart}<table width=\"95%\"  border=\"0\" cellpadding=\"0\" cellspacing=\"0\">{/dede:areastart}\r\n    {dede:areaend}<table width=\"639\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">{/dede:areaend}\r\n",162,712);
$z[1][4]['sourcetype']="hand";
$z[1][4]['rssurl']="http://";
$z[1][4]['regxurl']="http://";
$z[1][4]['startid']="1";
$z[1][4]['endid']="";
$z[1][4]['addv']="1";
$z[1][4]['urlrule']="area";
$z[1][4]['musthas']=".html";
$z[1][4]['nothas']="";
$z[1][4]['listpic']="1";
$z[1][4]['usemore']="0";

?>