<?php
$z[0]=Array("addurls","http://dangjian.zf11.com/Article/ShowClass.asp?ClassID=1&SpecialID=&page=2",6,109);
$z[1]=Array("batchrule","",115,148);
$z[2]=Array("regxrule","",154,185);
$z[3]=Array("areastart","<table width=\"95%\"  border=\"0\" cellpadding=\"0\" cellspacing=\"0\">",191,287);
$z[4]=Array("areaend","<table width=\"639\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">",293,384);

?>