<?php
$z[0]=Array("field","奥运火炬接力启动,胡锦涛主席点",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","奥运火炬接力启动 胡锦涛主席点燃圣火盆[暂无简介]",72,163);
$z[1][4]['name']="description";
$z[2]=Array("field","奥运火炬接力启动 胡锦涛主席点燃圣火盆",165,240);
$z[2][4]['name']="title";
$z[3]=Array("field","",242,281);
$z[3][4]['name']="writer";
$z[4]=Array("field","",283,322);
$z[4][4]['name']="source";
$z[5]=Array("field","<img src=\"/uploads/allimg/c111026/13196340R350-24502.jpg\" border=0>",324,428);
$z[5][4]['name']="body";
$z[6]=Array("field","",430,470);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","/uploads/allimg/c111026/13196340R350-24502_lit.jpg",472,561);
$z[7][4]['name']="litpic";

?>