{dede:field name='keywords'}奥运火炬接力启动,胡锦涛主席点{/dede:field}
{dede:field name='description'}奥运火炬接力启动 胡锦涛主席点燃圣火盆[暂无简介]{/dede:field}
{dede:field name='title'}奥运火炬接力启动 胡锦涛主席点燃圣火盆{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<img src="/uploads/allimg/c111026/13196340R350-24502.jpg" border=0>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c111026/13196340R350-24502_lit.jpg{/dede:field}
