<?php
$z[0]=Array("field","",58,86);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",88,117);
$z[1][4]['name']="typename";
$z[2]=Array("arclist","\r\n<tr><td align=\"left\"  class=\"line-i\">&nbsp;<img src=\"[field:global.cfg_templeturl/]/skin/images/ico.gif\"/>&nbsp;<a href=\"[field:arcurl /]\" title=\"标题：[field:fulltitle function='html2text(@me)'/]\r\n作者：[field:writer /]\r\n更新：[field:pubdate function='GetDateTimeMK(@me)'/]\r\n点击：[field:click/]\" target=\"_blank\">[field:title /]</a></td>\r\n<td align=\"right\"  class=\"line-i\"><font color=\"#999999\">[</font><font color=\"#999999\">[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</font><font color=\"#999999\">]</font></td></tr>\r\n",290,862);
$z[2][4]['row']="6";
$z[2][4]['titlelen']="38";

?>