<?php
$z[0]=Array("global","",53,83);
$z[0][4]['name']="cfg_templeturl";
$z[1]=Array("arcurl","",121,136);
$z[2]=Array("title","",151,191);
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("writer","",199,215);
$z[4]=Array("pubdate","",223,269);
$z[4][4]['function']="GetDateTimeMK(@me)";
$z[5]=Array("click","",277,291);
$z[6]=Array("title","",309,323);
$z[7]=Array("pubdate","",391,438);
$z[7][4]['function']="MyDate('Y-m-d',@me)";

?>