<?php
$z[0]=Array("field","四通党建网站管理系统常用功能介",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","四通党建网站管理系统常用功能介绍[暂无简介]",73,159);
$z[1][4]['name']="description";
$z[2]=Array("field","四通党建网站管理系统常用功能介绍",161,231);
$z[2][4]['name']="title";
$z[3]=Array("field","",233,272);
$z[3][4]['name']="writer";
$z[4]=Array("field","",274,313);
$z[4][4]['name']="source";
$z[5]=Array("field","",315,355);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<P><FONT face=\"Times New Roman\">四通党建网站管理系统常用功能介绍</FONT></P><P><FONT face=\"Times New Roman\">&nbsp;&nbsp;&nbsp; </FONT></P><P><FONT face=\"Times New Roman\">常用功能：</FONT></P><P><FONT face=\"Times New Roman\">1、网站栏目任意增加、删除与修改，栏目可化分多级子菜单，方便了组织部的用户按自已的要求进行栏目上的调整。</FONT></P><P><FONT face=\"Times New Roman\">2、专业的导航管理及首页栏目显示管理，用户可选择相关栏目在导航或首页版块上显示，即使不懂网站开发，也能很好的调整网站的版块及风格。</FONT></P><P><FONT face=\"Times New Roman\">3、LOGO、BANNER、版权信息、广告后台任意修改。</FONT></P><P><FONT face=\"Times New Roman\">4、通知公告、在线投票、下载、视频、留言、广告、专题等功能一一俱全。</FONT></P><P><FONT face=\"Times New Roman\">5、更多功能，大家在使用中慢慢体会...</FONT></P><P><FONT face=\"Times New Roman\"></FONT>&nbsp;</P><P><FONT face=\"Times New Roman\">本系统适合党建网站、组织部网站使用</FONT></P><P><FONT face=\"Times New Roman\"><BR>四通党建网站管理系统是全国最专业的党建网站、组织部网站、党建网站建设中心、组织部网站建设中心、专业提供党建网站设计、专业提供组织部网站设计、党建网站模板、组织部网站模板、党建网站源码、组织部网站源码、党建网站管理系统、组织部网站管理系统、党建网站建设方案、组织部网站建设方案</FONT></P>",357,1626);
$z[6][4]['name']="body";
$z[7]=Array("field","",1628,1667);
$z[7][4]['name']="litpic";

?>