{dede:field name='keywords'}公交车上如何反扒防扒,新闻,党建{/dede:field}
{dede:field name='description'}公交车上如何反扒防扒[暂无简介]{/dede:field}
{dede:field name='title'}公交车上如何反扒防扒{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<FONT class=article><P>&nbsp;&nbsp; 每年入冬后是公交车上失窃案的发案高峰期。在此，向读者介绍一些反扒防扒知识。</P><P>&nbsp;&nbsp;&nbsp; 一、小偷多在车站游动。一般不上车，而是聚在站台上，哪里人多往哪挤，有的手里还拿零钱假装等车，当乘客挤着上车时，他们会挤在人群里伺机作案。 </P><P>&nbsp;&nbsp;&nbsp; 二、假装糊涂。小偷多是二三人配合，一人堵住车门，假装问司机行车路线，将其他乘客挡住无法上车，其他乘客此时都急着上车，其同伙伺机身后作案。 </P><P>&nbsp;&nbsp;&nbsp; 三、前后游走。一般乘客是前门上车后门下车，而扒窃分子则是随着目标而移动，当他们已到后门，发现又有新目标上车时，就会反身向前挤，他们会前后乱窜，遇此情况乘客应高度重视。 </P><P>&nbsp;&nbsp;&nbsp; 四、以物遮盖。小偷作案时手中常拿有报纸或手臂搭件衣服，或提一个塑料袋内装废纸、衣服等，也有拿手机包的。（编辑：刘阳）</P></FONT>{/dede:field}
{dede:field name='litpic'}{/dede:field}
