{dede:field name='keywords'}省公安厅公开悬赏通缉110名在逃{/dede:field}
{dede:field name='description'}省公安厅公开悬赏通缉110名在逃犯罪嫌疑人[暂无简介]{/dede:field}
{dede:field name='title'}省公安厅公开悬赏通缉110名在逃犯罪嫌疑人{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<P><FONT class=article>广东省公安厅日前发出今年第98号通缉令，对110名涉嫌严重刑事犯罪的在逃人员予以通缉，要求各地公安机关立即部署查缉工作。这是广东省公安机关深入开展命案侦破工作，发动社会群众参与，加大追逃打击力度而采取的重要措施。</FONT></P><P><FONT class=article>&nbsp;&nbsp;&nbsp; 通缉令说，任何公民发现被通缉的犯罪嫌疑人，均可立即将其扭送公安机关，司法机关处理。凡直接扭送或提供线索协助抓获一名被通缉人员的公民，由省公安厅奖励人民币5000元，并对举报人绝对保密。</FONT></P>{/dede:field}
{dede:field name='litpic'}{/dede:field}
