<?php
$z[0]=Array("field","",32,61);
$z[0][4]['name']="typename";
$z[1]=Array("arclist","\r\n	¡¤<a href=\"[field:arcurl /]\" title=\"[field:fulltitle function='html2text(@me)'/]\" target=\"_blank\">[field:title /]<br />\r\n	 <div align=\"right\">[field:pubdate function=\"MyDate('m-d',@me)\"/]&nbsp;&nbsp;</a></div><div class=\"anline\">&nbsp;</div>\r\n      ",305,608);
$z[1][4]['titlelen']="40";
$z[1][4]['row']="8";

?>