<?php
$z[0]=Array("typelink","",105,123);
$z[1]=Array("typename","",125,143);
$z[2]=Array("arcurl","",170,186);
$z[3]=Array("fulltitle","",201,245);
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("writer","",253,269);
$z[5]=Array("pubdate","",277,323);
$z[5][4]['function']="GetDateTimeMK(@me)";
$z[6]=Array("click","",331,345);
$z[7]=Array("title","",363,378);
$z[8]=Array("pubdate","",478,525);
$z[8][4]['function']="MyDate('Y-m-d',@me)";

?>