{dede:field name='keywords'}阿拉木图民众迎圣火,世界人民的{/dede:field}
{dede:field name='description'}阿拉木图民众迎圣火 世界人民的共同盛会[暂无简介]{/dede:field}
{dede:field name='title'}阿拉木图民众迎圣火 世界人民的共同盛会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<P><img src="/uploads/allimg/c111026/13196340Z330-31S7.jpg" border=0></P><P>　4月2日，阿拉木图民众在阿斯塔纳广场外等待奥运圣火到来。当日，北京奥运会火炬传递活动在哈萨克斯坦最大城市阿拉木图进行，跨越五大洲的奥运圣火境外之旅由此拉开帷幕。新华社记者安治平摄</P>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c111026/13196340Z330-31S7_lit.jpg{/dede:field}
