<?php
$z[0]=Array("field","阿拉木图民众迎圣火,世界人民的",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","阿拉木图民众迎圣火 世界人民的共同盛会[暂无简介]",72,163);
$z[1][4]['name']="description";
$z[2]=Array("field","阿拉木图民众迎圣火 世界人民的共同盛会",165,240);
$z[2][4]['name']="title";
$z[3]=Array("field","",242,281);
$z[3][4]['name']="writer";
$z[4]=Array("field","",283,322);
$z[4][4]['name']="source";
$z[5]=Array("field","<P><img src=\"/uploads/allimg/c111026/13196340Z330-31S7.jpg\" border=0></P><P>　4月2日，阿拉木图民众在阿斯塔纳广场外等待奥运圣火到来。当日，北京奥运会火炬传递活动在哈萨克斯坦最大城市阿拉木图进行，跨越五大洲的奥运圣火境外之旅由此拉开帷幕。新华社记者安治平摄</P>",324,619);
$z[5][4]['name']="body";
$z[6]=Array("field","",621,661);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","/uploads/allimg/c111026/13196340Z330-31S7_lit.jpg",663,751);
$z[7][4]['name']="litpic";

?>