{dede:noteinfo notename="ĞÂÎÅ" channelid="1" macthtype="string"
    refurl="http://" sourcelang="gb2312" cosort="asc"
  isref="no" exptime="10" usemore="0" /}
{dede:listrule sourcetype="hand" rssurl="http://" regxurl="http://"
startid="1" endid="" addv="1" urlrule="area" musthas=".html"
 nothas="" listpic="1" usemore="0"}
    {dede:addurls}http://dangjian.zf11.com/Article/ShowClass.asp?ClassID=6{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<table width="95%"  border="0" cellpadding="0" cellspacing="0">{/dede:areastart}
    {dede:areaend}<table width="639" border="0" cellpadding="0" cellspacing="0">{/dede:areaend}
{/dede:listrule}
