<?php
$z[0]=Array("global","",280,309);
$z[0][4]['name']="cfg_templeturl";
$z[1]=Array("field","",435,463);
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",472,501);
$z[2][4]['name']="typename";
$z[3]=Array("field","",503,532);
$z[3][4]['name']="typename";
$z[4]=Array("field","",596,624);
$z[4][4]['name']="typeurl";
$z[5]=Array("global","",636,665);
$z[5][4]['name']="cfg_templeturl";
$z[6]=Array("global","",819,848);
$z[6][4]['name']="cfg_templeturl";
$z[7]=Array("arclist","\r\n<tr><td align=\"left\"  class=\"line-i\">&nbsp;<img src=\"[field:global.cfg_templeturl/]/skin/images/ico.gif\"/>&nbsp;<a href=\"[field:arcurl /]\" title=\"标题：[field:fulltitle function='html2text(@me)'/]\r\n作者：[field:writer /]\r\n更新：[field:pubdate function='GetDateTimeMK(@me)'/]\r\n点击：[field:click/]\" target=\"_blank\">[field:title /]</a></td>\r\n<td align=\"right\"  class=\"line-i\"><font color=\"#999999\">[</font><font color=\"#999999\">[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</font><font color=\"#999999\">]</font></td></tr>\r\n      ",1108,1689);
$z[7][4]['titlelen']="60";
$z[7][4]['row']="7";
$z[8]=Array("global","if(@me%2==0)@me='</tr><tr><td colspan=\"3\" align=\"center\" height=\"8\"></td></tr><tr>';else @me='<td width=\"5\"></td>';",1746,1918);
$z[8][4]['name']="itemindex";
$z[8][4]['runphp']="yes";

?>