<?php
$z[0]=Array("field","活动广告车被查,新闻,城管网站,",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","活动广告车被查[暂无简介]",72,140);
$z[1][4]['name']="description";
$z[2]=Array("field","活动广告车被查",142,194);
$z[2][4]['name']="title";
$z[3]=Array("field","",196,235);
$z[3][4]['name']="writer";
$z[4]=Array("field","",237,276);
$z[4][4]['name']="source";
$z[5]=Array("field","",278,318);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","昨天，在丰台区万源北路,这辆改装过的电动车拉着“北京某妇康门诊部”的广告满大街跑。 <BR>　　当日，认定该改装车上的广告属于户外广告的一种，丰台城管东高地分队将该车暂扣，并进一步调查此事。 <BR>",320,546);
$z[6][4]['name']="body";
$z[7]=Array("field","",548,587);
$z[7][4]['name']="litpic";

?>