{dede:field name='keywords'}活动广告车被查,新闻,城管网站,{/dede:field}
{dede:field name='description'}活动广告车被查[暂无简介]{/dede:field}
{dede:field name='title'}活动广告车被查{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}昨天，在丰台区万源北路,这辆改装过的电动车拉着“北京某妇康门诊部”的广告满大街跑。 <BR>　　当日，认定该改装车上的广告属于户外广告的一种，丰台城管东高地分队将该车暂扣，并进一步调查此事。 <BR>{/dede:field}
{dede:field name='litpic'}{/dede:field}
