<?php
$z[0]=Array("global","",47,77);
$z[0][4]['name']="cfg_templeturl";
$z[1]=Array("arcurl","",109,124);
$z[2]=Array("fulltitle","",139,183);
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("writer","",191,207);
$z[4]=Array("pubdate","",215,261);
$z[4][4]['function']="GetDateTimeMK(@me)";
$z[5]=Array("click","",269,283);
$z[6]=Array("title","",301,315);
$z[7]=Array("pubdate","",383,430);
$z[7][4]['function']="MyDate('Y-m-d',@me)";

?>