<tr><td align="left"  class="line-i"><img src="[field:global.cfg_templeturl/]/skin/images/ico.gif"/><a href="[field:arcurl/]" title="标题：[field:fulltitle function='html2text(@me)'/]
作者：[field:writer /]
更新：[field:pubdate function='GetDateTimeMK(@me)'/]
点击：[field:click/]" target="_blank">[field:title/]</a></td>
<td align="right"  class="line-i"><font color="#999999">[[field:pubdate function="MyDate('Y-m-d',@me)"/]]</font></td></tr>