<?php
$z[0]=Array("sppage","",0,59);
$z[0][4]['sptype']="full";
$z[0][4]['srul']="1";
$z[0][4]['erul']="5";
$z[1]=Array("previewurl","http://dangjian.zf11.com/zf/Article/270.html",61,140);
$z[2]=Array("keywordtrim","",142,179);
$z[3]=Array("descriptiontrim","",181,226);
$z[4]=Array("item","\r\n   {dede:match}<td align=\"center\" valign=\"middle\"><h1>[ÄÚÈÝ]</h1></td>{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",228,422);
$z[4][4]['field']="title";
$z[4][4]['value']="";
$z[4][4]['isunit']="";
$z[4][4]['isdown']="";
$z[5]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",422,562);
$z[5][4]['field']="writer";
$z[5][4]['value']="";
$z[5][4]['isunit']="";
$z[5][4]['isdown']="";
$z[6]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",562,702);
$z[6][4]['field']="source";
$z[6][4]['value']="";
$z[6][4]['isunit']="";
$z[6][4]['isdown']="";
$z[7]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",702,843);
$z[7][4]['field']="pubdate";
$z[7][4]['value']="";
$z[7][4]['isunit']="";
$z[7][4]['isdown']="";
$z[8]=Array("item","\r\n   {dede:match}<DIV class=Content id=fontzoom style=\"FONT-SIZE: 14px; LINE-HEIGHT: 32px\">[ÄÚÈÝ]</td>\r\n              </tr>\r\n            </table></td></tr>{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",843,1121);
$z[8][4]['field']="body";
$z[8][4]['value']="";
$z[8][4]['isunit']="1";
$z[8][4]['isdown']="1";

?>