{dede:field name='keywords'}公安部消防局督察组赴各地进行检{/dede:field}
{dede:field name='description'}公安部消防局督察组赴各地进行检查督导[暂无简介]{/dede:field}
{dede:field name='title'}公安部消防局督察组赴各地进行检查督导{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<P><FONT class=article>　为大力推进高层建筑、公众聚集场所和地下建筑消防安全专项整治行动深入开展，全面扎实做好各项灭火救援准备，进一步提升公安消防部队灭火救援攻坚能力，公安部消防局从局机关和部分省市消防总队抽调战训业务骨干组成五个督察组，从4月21日至5月20日对各地高层建筑、公众聚集场所和地下建筑灭火救援准备等工作进行检查督导。<BR>&nbsp;<BR>　　督察工作将采取查看工作记录、实地测试、组织演练、提问指导等方式进行督察。督察内容包括：各地高层建筑、地下建筑、公众聚集场所调查摸底，车辆装备性能、技术战术实地测试，开展专业培训和战例研讨，灭火救援专用装备配置及专业队伍建设，灭火救援战勤保障等灭火救援准备情况，各地“五一”期间消防安全保卫工作部署和防范措施、执勤备战、重点单位和场所熟悉演练等工作。 </FONT></P><P><FONT class=article>　　4月20日，公安部消防局召开督察组全体人员会议，对督察的重点内容、实施方法等进行了培训和部署，要求各督察组务必高度重视，周密组织；强化措施，确保安全；加强报告，跟踪指导；恪尽职守，严格要求，确保督察工作取得实效。（来自公安部网站）&nbsp;</FONT></P>{/dede:field}
{dede:field name='litpic'}{/dede:field}
