{dede:field name='keywords'}电动车推着走被扣罚,新闻,党建网{/dede:field}
{dede:field name='description'}电动车推着走被扣罚[暂无简介]{/dede:field}
{dede:field name='title'}电动车推着走被扣罚{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<P><FONT class=article>“刚买了不到10分钟，准备春节运回老家给儿子，不想却被扣了车，何况我并没有骑！”拿着一纸罚单，在广州海珠打工的龚先生一脸无奈，本想把这辆电动车当新年礼物，送给远在重庆的儿子的。而海珠交警大队的解释是，只要电动车上了路，不管是骑着还是推着，都是不允许的。</FONT></P><P><FONT class=article>&nbsp;&nbsp;&nbsp; 日前，龚先生花了1200元，在海珠区墩和一家档口，买了辆电动自行车。在龚先生看来，这是给儿子的最好的新年礼物，在他老家重庆郊区，一来电动车不好买、二来价钱又高，“不如在广州买一辆，过几天托运回去，儿子一直想要。”</FONT></P><P><FONT class=article>&nbsp;&nbsp;&nbsp; 据龚先生说，买完车后，他一直推着走，可即便如此，不到10分钟后，交警就出现在他面前，随即把车拖走了。“说要罚款，让我过两天去取回来！”令龚先生不满的是，自己既没有骑也不会骑电动车，且当时刚推了几十米，不应该受到处罚。</FONT></P><P><FONT class=article>&nbsp;&nbsp;&nbsp; 随后的几天内，龚师傅连跑了几趟交警大队，本周二又去办了处罚手续。“据说要罚1000多元！”</FONT></P><P><FONT class=article>&nbsp;&nbsp;&nbsp; 据海珠交警大队工作人员称，他们每天都会抓到不少电动车，许多车主被抓后，会找各种理由想要回车子。根据广州市公安局有关规定，只要电动自行车上路行驶，就属于违规行为，交警就有权依法予以处理。像龚先生这样，若其直接托运回老家而非上路，则不属处罚范围。（单小亮 编辑：刘阳）</FONT></P>{/dede:field}
{dede:field name='litpic'}{/dede:field}
