<?php
$z[0]=Array("global","",53,83);
$z[0][4]['name']="cfg_templeturl";
$z[1]=Array("arcurl","",121,137);
$z[2]=Array("fulltitle","",152,196);
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("writer","",204,220);
$z[4]=Array("pubdate","",228,274);
$z[4][4]['function']="GetDateTimeMK(@me)";
$z[5]=Array("click","",282,296);
$z[6]=Array("title","",314,329);
$z[7]=Array("pubdate","",426,473);
$z[7][4]['function']="MyDate('Y-m-d',@me)";

?>