{dede:field name='keywords'}婚车遮挡号牌属交通违法行为,新{/dede:field}
{dede:field name='description'}婚车遮挡号牌属交通违法行为[暂无简介]{/dede:field}
{dede:field name='title'}婚车遮挡号牌属交通违法行为{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<P><FONT class=article>&nbsp;&nbsp; 牌照贴上“永结同心”、“百年好合”等字样，婚车就大摇大摆上了路。在老百姓眼里，婚车遮挡车牌已经司空见惯。殊不知，遮挡车牌属于交通违法行为。近日，南雄市公安交警大队雄州中队对遮挡车牌的婚车进行了专项查处。</FONT></P><P><FONT class=article>&nbsp;&nbsp;&nbsp; 16日，又是农历吉日，迎亲车队随处可见，用红色彩纸遮挡号牌更是屡见不鲜，雄州中队曾海中队长立即带领数名民警走上路面，把目标锁定在一些婚庆礼仪公司和摄影店，耐心地向店主和司机说明遮挡车牌属于交通违法行为，根据《道路交通安全法》的相关规定，司机故意遮挡车牌要被处以罚款200元并记6分的处罚。民警把粘贴在牌照上面的红色纸揭掉，贴到其他位置，用摄像机取证，对司机进行了教育。</FONT></P><P><FONT class=article>&nbsp;&nbsp;&nbsp; 交警执法管理以人为本！在查处时，某男子说，婚车遮牌“很正常”，一般都是贴上，大小宽度与车牌一致，贴写有祝福语的红纸，也是一种喜庆气氛。而且，可以遮挡一些“不吉利”的车牌。“结婚是一件大事，谁不想图个吉利？”中队长曾海称，在以往的执勤中，发现有一些婚车，婚礼已经举行过两三天了，遮挡车牌的红纸还没有去掉，更是有些车主纯粹是为了逃避电子监控而伪装成婚庆车辆。不论是出于何种目的，遮挡车牌都是属于交通违法行为，是不允许的，我们之所以采取在婚车布置时进行取证查处，也是出于人性化管理，因为在路面上拦停婚庆车队，逐一现场处罚必定会影响道路畅通，也会影响婚礼准时举行。（陈红虹 谢俊玲编辑：小婷）</FONT></P>{/dede:field}
{dede:field name='litpic'}{/dede:field}
