{dede:field name='keywords'}公安机关提醒市民,警惕“刷卡消{/dede:field}
{dede:field name='description'}公安机关提醒市民 警惕“刷卡消费”短信诈骗[暂无简介]{/dede:field}
{dede:field name='title'}公安机关提醒市民 警惕“刷卡消费”短信诈骗{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<P><FONT class=article>近日，“刷卡消费”短信诈骗又有卷土重来之势。江门台山公安机关提醒市民提高警惕，不要回复此类电话，可将短信直接转发公安部门报警服务台，向派出所报案。</FONT></P><P><FONT class=article>　　谭先生在2月24日收到一条信息，称其在江门新一佳百货消费9568元，并附联系电话，谭先生感到很奇怪，故打电话咨询。电话中，有位男子称谭先生银行资料被外泄，让他到工商银行自动柜员机处升级。让谭先生没想到的是，他按照这名男子所说的方法“升级”后，卡内的2万元现金被转到了其他账号，谭先生这才发现自己被诈骗。</FONT></P><P><FONT class=article>　　据了解，在此类诈骗中，不法分子首先会利用手机发送短信，一旦事主与其联系，不法分子就会让事主转账、开户存钱。若有人怀疑，不法分子还会以假的报警电话、假的“银行银联卡中心”让事主消除顾虑，事主消除顾虑后就会“听话”地用自动取款机进行转账、存钱。</FONT></P><P><FONT class=article>　　警方建议，对这种不是很明确的陌生电话号码，持卡人不要拨打，而应及时跟发卡银行或中国银联联系，以确认信息来源。　（区景常 台公宣）</FONT></P>{/dede:field}
{dede:field name='litpic'}{/dede:field}
