{dede:field name='keywords'}党的文献工作要更好为党思想理论{/dede:field}
{dede:field name='description'}党的文献工作要更好为党思想理论建设服务[暂无简介]{/dede:field}
{dede:field name='title'}党的文献工作要更好为党思想理论建设服务{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<FONT id=Zoom>&nbsp;新华社北京２月２５日电（记者谭浩）中国中共文献研究会２５日在北京召开成立大会。中共中央政治局常委、中央书记处书记、国家副主席习近平出席大会并作重要讲话。他指出，我们党在长期奋斗历程中形成的大量文献特别是党的主要领导人的重要文献，记录了党在革命、建设和改革实践中艰辛探索的奋斗历史，记录了党在不同历史条件下完成伟大艰巨任务积累的宝贵经验，记录了马克思主义中国化的理论成果和历史进程，是几代中国共产党人智慧的结晶，是我们治党治国宝贵的政治和精神财富。</FONT>{/dede:field}
{dede:field name='litpic'}{/dede:field}
