{dede:field name='keywords'}阿坝暴力事件致200多名政府人员{/dede:field}
{dede:field name='description'}阿坝暴力事件致200多名政府人员和民警受伤[暂无简介]{/dede:field}
{dede:field name='title'}阿坝暴力事件致200多名政府人员和民警受伤{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<P><img src="/uploads/allimg/c111027/1319645D11Z-14F9.jpg" border=0></P><P>&nbsp;</P>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c111027/1319645D11Z-14F9_lit.jpg{/dede:field}
