<?php
$z[0]=Array("field","阿坝暴力事件致200多名政府人员",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","阿坝暴力事件致200多名政府人员和民警受伤[暂无简介]",72,165);
$z[1][4]['name']="description";
$z[2]=Array("field","阿坝暴力事件致200多名政府人员和民警受伤",167,244);
$z[2][4]['name']="title";
$z[3]=Array("field","",246,285);
$z[3][4]['name']="writer";
$z[4]=Array("field","",287,326);
$z[4][4]['name']="source";
$z[5]=Array("field","",328,368);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<P><img src=\"/uploads/allimg/c111027/1319645D11Z-14F9.jpg\" border=0></P><P>&nbsp;</P>",370,492);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c111027/1319645D11Z-14F9_lit.jpg",494,581);
$z[7][4]['name']="litpic";

?>