<tr>
        <td class="leftTitle1">{dede:field name='typename'/}</td>
      </tr>
      <tr>
        <td height="230" align="left" valign="top" class="leftBottomBg">
		<div class="downnews">
			<table width="100%" border="0" cellpadding="0" cellspacing="0" class="line-i">
			 {dede:arclist titlelen='60' row='8'}
				<tr><td align="left"  class="line-i">&nbsp;<img src="[field:global.cfg_templeturl/]/skin/images/ico.gif"/>&nbsp;<a href="[field:arcurl /]" title="[field:fulltitle function='html2text(@me)'/]" target="_blank">[field:title /]</a></td></tr>
			    {/dede:arclist}
			</table>
		</div></td>
      </tr>