<?php
$z[0]=Array("specnote","\r\n                <li><span class=\"date\">[field:typename/]</span><a href=\"[field:arcurl /]\" target=\"_blank\">[field:title /]</a></li>\r\n                ",0,506);
$z[0][4]['imgheight']="90";
$z[0][4]['imgwidth']="120";
$z[0][4]['infolen']="160";
$z[0][4]['titlelen']="60";
$z[0][4]['col']="1";
$z[0][4]['idlist']="135,134,133,132,131,130,129,128,127,126,125,124,123,122,121,120,119,118,117,116,115,114,113,112,111,110,109,108,107,106";
$z[0][4]['name']="д╛хо╫з╣Ц";
$z[0][4]['noteid']="default";
$z[0][4]['isauto']="0";
$z[0][4]['rownum']="20";
$z[0][4]['keywords']="";
$z[0][4]['typeid']="0";

?>