{dede:specnote imgheight='90' imgwidth='120'
                infolen='160' titlelen='60' col='1' idlist='135,134,133,132,131,130,129,128,127,126,125,124,123,122,121,120,119,118,117,116,115,114,113,112,111,110,109,108,107,106'
                name='д╛хо╫з╣Ц' noteid='default' isauto='0' rownum='20'
                keywords='' typeid='0'}
                <li><span class="date">[field:typename/]</span><a href="[field:arcurl /]" target="_blank">[field:title /]</a></li>
                {/dede:specnote}
