<?php
$z[0]=Array("field","奥运火炬伊斯坦布尔传递,护火手",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","奥运火炬伊斯坦布尔传递 护火手展示火种灯[暂无简介]",72,165);
$z[1][4]['name']="description";
$z[2]=Array("field","奥运火炬伊斯坦布尔传递 护火手展示火种灯",167,244);
$z[2][4]['name']="title";
$z[3]=Array("field","",246,285);
$z[3][4]['name']="writer";
$z[4]=Array("field","",287,326);
$z[4][4]['name']="source";
$z[5]=Array("field","<P><img src=\"/uploads/allimg/c111026/13196340D640-164W.jpg\" border=0></P><P>　4月3日，在圣火传递终点――塔克希姆广场，护火手展示火种灯。当日，<A class=akey href=\"http://2008.sina.com.cn/\" target=_blank>北京奥运会</A>圣火境外传递第二站在土耳其伊斯坦布尔结束。 </P><P>　　新华社记者郭磊摄</P>",328,655);
$z[5][4]['name']="body";
$z[6]=Array("field","",657,697);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","/uploads/allimg/c111026/13196340D640-164W_lit.jpg",699,787);
$z[7][4]['name']="litpic";

?>