{dede:field name='keywords'}奥运火炬伊斯坦布尔传递,护火手{/dede:field}
{dede:field name='description'}奥运火炬伊斯坦布尔传递 护火手展示火种灯[暂无简介]{/dede:field}
{dede:field name='title'}奥运火炬伊斯坦布尔传递 护火手展示火种灯{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<P><img src="/uploads/allimg/c111026/13196340D640-164W.jpg" border=0></P><P>　4月3日，在圣火传递终点――塔克希姆广场，护火手展示火种灯。当日，<A class=akey href="http://2008.sina.com.cn/" target=_blank>北京奥运会</A>圣火境外传递第二站在土耳其伊斯坦布尔结束。 </P><P>　　新华社记者郭磊摄</P>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c111026/13196340D640-164W_lit.jpg{/dede:field}
