{dede:field name='keywords'}马凯在中国海上搜救中心总值班室{/dede:field}
{dede:field name='description'}马凯在中国海上搜救中心总值班室听取汇报[暂无简介]{/dede:field}
{dede:field name='title'}马凯在中国海上搜救中心总值班室听取汇报{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}中央国家机关工委在交通运输部召开中央国家机关部分部门学习实践科学发展观活动座谈会。国务委员兼国务院秘书长、中央国家机关工委书记马凯出席会议并作重要讲话。他强调，整改落实阶段是学习实践活动的关键阶段，是最能体现实践特色、最能反映学习成果的阶段。中央国家机关各部门要认真学习贯彻胡锦涛总书记和其他中央领导同志关于做好整改落实阶段工作的指示精神，扎实做好整改落实阶段各项工作，不断把学习实践活动引向深入，确保取得实实在在的效果。{/dede:field}
{dede:field name='litpic'}{/dede:field}
