<?php
$z[0]=Array("field","以无限忠诚谱写人生之歌,公安网",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","以无限忠诚谱写人生之歌[暂无简介]",72,148);
$z[1][4]['name']="description";
$z[2]=Array("field","以无限忠诚谱写人生之歌",150,210);
$z[2][4]['name']="title";
$z[3]=Array("field","",212,251);
$z[3][4]['name']="writer";
$z[4]=Array("field","",253,292);
$z[4][4]['name']="source";
$z[5]=Array("field","<img src=\"http://dangjian.zf11.com/zf/17/vipzf21/UpLoadFiles/Article/2009-5/2009052215193464703.jpg\" border=0>",294,441);
$z[5][4]['name']="body";
$z[6]=Array("field","",443,483);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",485,524);
$z[7][4]['name']="litpic";

?>