{dede:field name='keywords'}以无限忠诚谱写人生之歌,公安网{/dede:field}
{dede:field name='description'}以无限忠诚谱写人生之歌[暂无简介]{/dede:field}
{dede:field name='title'}以无限忠诚谱写人生之歌{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<img src="http://dangjian.zf11.com/zf/17/vipzf21/UpLoadFiles/Article/2009-5/2009052215193464703.jpg" border=0>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
