<div class="picBox2">
<div class="picTitle"><span class="right"><a href="{dede:field name='typeurl'/}">更多&lt;&lt;</a></span>{dede:field name='typename'/}</div>
<div class="picShow">
<table width="100%" cellpadding="0" cellspacing="0" border="0" align="center">
<tr valign="top">
      {dede:arclist titlelen='20' row='4' type='image.'}
	<td align="center"  class="line-i"><a href="[field:arcurl/]" title="标题：[field:fulltitle function='html2text(@me)'/]
作者：[field:writer /]
更新：[field:pubdate function='GetDateTimeMK(@me)'/]
点击：[field:click/]" target="_blank"><img src="[field:litpic/]" width="124" height="97" border="0" style="margin-right:10px;" alt="" /><br />[field:title /]...</a></td>
{/dede:arclist}
</tr></table>
</div>
</div>