<?php
$z[0]=Array("field","",74,102);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",127,156);
$z[1][4]['name']="typename";
$z[2]=Array("arclist","\r\n	<td align=\"center\"  class=\"line-i\"><a href=\"[field:arcurl/]\" title=\"标题：[field:fulltitle function='html2text(@me)'/]\r\n作者：[field:writer /]\r\n更新：[field:pubdate function='GetDateTimeMK(@me)'/]\r\n点击：[field:click/]\" target=\"_blank\"><img src=\"[field:litpic/]\" width=\"124\" height=\"97\" border=\"0\" style=\"margin-right:10px;\" alt=\"\" /><br />[field:title /]...</a></td>\r\n",292,729);
$z[2][4]['titlelen']="20";
$z[2][4]['row']="4";
$z[2][4]['type']="image.";

?>