{dede:field name='keywords'}郑州天价理发馆被勒令停业整顿,{/dede:field}
{dede:field name='description'}郑州天价理发馆被勒令停业整顿[暂无简介]{/dede:field}
{dede:field name='title'}郑州天价理发馆被勒令停业整顿{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<P><img src="/uploads/allimg/c111027/1319645EC30-41061.jpg" border=0></P><P>昨日下午5时40分，在围观群众的一片掌声中，工商部门执法人员宣布保罗国际停业整顿。 </P><P>　　然而，事情并没有就此结束，两名女生的家长为了讨回近万元的冤枉钱，委托商报寻找代理律师进行起诉。</P><P><STRONG>　　店门口闪客举牌抗议</STRONG></P><P>　　“天价头”事件中，店员的态度以及问题迟迟不解决等，遭到很多人抗议。</P><P>　　昨日下午6时30分，有一群反对“天价头”的闪客出现在理发店门口，他们的行为将反对“天价头”情绪推向高潮。</P><P>　　这一群由大河网-大河论坛的网友自发组成的闪客行动，在保罗国际门口举行抗议活动。他们将写着“很黑很后台”的十六开纸举在头顶，表示他们对保罗国际的不满。</P><P>　　大河网友007告诉记者：“这种欺诈、勒索行为出现在郑州，而且长期存在，是给郑州抹黑，给河南人抹黑，这对郑州今年参加全国文明城市评选极为不利。”</P><P>　　最后在执法人员的劝解下，网友在热烈的掌声中散去。</P>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c111027/1319645EC30-41061_lit.jpg{/dede:field}
