<?php
$z[0]=Array("field","文件签收,新闻,党建网站模板下载",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","文件签收[暂无简介]",73,135);
$z[1][4]['name']="description";
$z[2]=Array("field","文件签收",137,183);
$z[2][4]['name']="title";
$z[3]=Array("field","",185,224);
$z[3][4]['name']="writer";
$z[4]=Array("field","",226,265);
$z[4][4]['name']="source";
$z[5]=Array("field","",267,307);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<script type='text/Javascript' src='/Article/GetContent.asp?ArticleID=152'></script>",309,430);
$z[6][4]['name']="body";
$z[7]=Array("field","",432,471);
$z[7][4]['name']="litpic";

?>