picarry[[field:global name=autoindex runphp='yes']@me=@me-1;[/field:global]]="[field:litpic/]";
ttlarry[[field:global name=autoindex runphp='yes']@me=@me-1;[/field:global]] = "[field:title function='html2text(@me)'/]";
lnkarry[[field:global name=autoindex runphp='yes']@me=@me-1;[/field:global]]  = "[field:arcurl/]";
ttlarry[[field:global name=autoindex runphp='yes']@me=@me-1;[/field:global]] = "[field:title function='html2text(@me)'/]";