<?php
$z[0]=Array("global","",236,271);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("global","",284,317);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",348,377);
$z[2][4]['name']="cfg_templeturl";
$z[3]=Array("include","",569,604);
$z[3][4]['filename']="head.htm";
$z[4]=Array("global","",784,818);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("global","",856,885);
$z[5][4]['name']="maplist";
$z[6]=Array("include","",909,946);
$z[6][4]['filename']="footer.htm";

?>