<?php
$z[0]=Array("global","",236,264);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("global","",285,311);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",352,381);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",421,479);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",497,526);
$z[4][4]['name']="cfg_templeturl";
$z[5]=Array("global","",742,767);
$z[5][4]['name']="cfg_cmsurl";
$z[6]=Array("include","",835,870);
$z[6][4]['filename']="head.htm";
$z[7]=Array("tag","\r\n            <a href='[field:link/]' class='tagc[field:highlight /]'>[field:tag /]</a>\r\n            ",1126,1268);
$z[7][4]['row']="60";
$z[7][4]['sort']="new";
$z[8]=Array("tag","\r\n            <a href='[field:link/]' class='tagc[field:highlight /]'>[field:tag /]</a>\r\n            ",1416,1560);
$z[8][4]['row']="60";
$z[8][4]['sort']="month";
$z[9]=Array("tag","\r\n            <a href='[field:link/]' class='tagc[field:highlight /]'>[field:tag /]</a>\r\n            ",1704,1848);
$z[9][4]['row']="100";
$z[9][4]['sort']="rand";
$z[10]=Array("include","",1891,1928);
$z[10][4]['filename']="footer.htm";

?>